import "./globals.css";

import type { Metadata } from "next";

import { Poppins, Nunito } from "next/font/google";

import { cn } from "@/lib/utils";

import { ClerkProvider, auth } from "@clerk/nextjs";
import { dark, neobrutalism } from "@clerk/themes";

import ContextProvider from "@/providers/contextProvider";

import NextTopLoader from "nextjs-toploader";

import Sidebar from "@/components/sidebar";

import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/theme-provider";

const poppins = Poppins({
    weight: ["400", "500", "600", "700", "800"],
    subsets: ["latin"],
});

const nunito = Nunito({
    weight: ["400", "500", "600", "700", "800"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const { userId } = auth();

    return (
        <ClerkProvider appearance={{ baseTheme: dark }}>
            <html lang="en" className="h-full bg-background">
                <body className={cn(nunito.className, "h-full bg-background")}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <NextTopLoader
                            height={2}
                            color="#27AE60"
                            easing="cubic-bezier(0.53,0.21,0,1)"
                        />
                        <ContextProvider>
                            <div className="main">
                                {userId && <Sidebar />}
                                <div className="w-full">{children}</div>
                            </div>
                            <Toaster
                                theme="dark"
                                toastOptions={{
                                    style: {
                                        background: "#2a2e35",
                                    },
                                }}
                            />
                        </ContextProvider>
                    </ThemeProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
